# Generated by Django 4.2.3 on 2023-07-29 06:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
